version: '3.8'

services:
  # Banco PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: api_postgres
    environment:
      POSTGRES_DB: api_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - api_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d api_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Aplicação Node.js
  api:
    build: .
    container_name: api_app
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: api_db
      DB_USER: postgres
      DB_PASSWORD: password
    ports:
      - "3001:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - api_network
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  # PgAdmin (opcional - interface web para PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: api_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - api_network

networks:
  api_network:
    driver: bridge